# Generated by Django 4.2 on 2025-07-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='gold_holdings',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=15),
        ),
    ]
